<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Authors>Marcus Vinicius de Freitas Costa</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://www.nuget.org/packages/MVFC.Pack.Cache</PackageProjectUrl>
    <PackageTags>cache;redis;hybrid-cache;distributed-cache;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/Marcus-V-Freitas/MVFC.Pack.Cache</RepositoryUrl>
    <Description>Metapackage projetado para simplificar e padronizar a implementação de cache distribuído em aplicações .NET 9 | 10, combinando Redis e Hybrid Cache.</Description>
    <IncludeSymbols>false</IncludeSymbols>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddPlaceholderFile</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="StackExchange.Redis" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
	<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="AddPlaceholderFile">
    <Touch Files="$(IntermediateOutputPath)_._" AlwaysCreate="true" />
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(IntermediateOutputPath)_._">
        <PackagePath>lib/$(TargetFramework)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>

</Project>
