<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Version>0.0.0</Version>
    <Authors>Marcus Vinicius de Freitas Costa</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://www.nuget.org/packages/MVFC.Pack.Api</PackageProjectUrl>
    <PackageTags>api;dotnet;metapackage;refit;serilog;fluentvalidation;fluentresults;jwt;openapi</PackageTags>
    <RepositoryUrl>https://github.com/Marcus-V-Freitas/MVFC.Pack.Api</RepositoryUrl>
    <Description>Metapackage para padronizar e acelerar o desenvolvimento de APIs no ecossistema .NET 9 | 10. Inclui ferramentas para resiliência (Refit), validação (FluentValidation), logs estruturados (Serilog) e segurança (JWT).</Description>
    <IncludeSymbols>false</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Serilog.AspNetCore" />
      <PackageReference Include="Serilog.Sinks.File" />
	  <PackageReference Include="Serilog.Sinks.Console" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Asp.Versioning.Http" />
      <PackageReference Include="AspNetCore.Scalar" />
      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="AddPlaceholderFile" BeforeTargets="_GetPackageFiles">
    <Touch Files="$(IntermediateOutputPath)_._" AlwaysCreate="true" />
    <ItemGroup>
      <None Include="$(IntermediateOutputPath)_._" Pack="true" PackagePath="lib/$(TargetFramework)/_._" />
    </ItemGroup>
  </Target>

</Project>
