<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Authors>Marcus Vinicius de Freitas Costa</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://www.nuget.org/packages/MVFC.Pack.Domain</PackageProjectUrl>
    <PackageTags>domain;mediator;refit;fluentvalidation;fluentresults;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/Marcus-V-Freitas/MVFC.Pack.Domain</RepositoryUrl>
    <Description>Metapackage para padronizar e acelerar o desenvolvimento de camadas de domínio em aplicações .NET 9 | 10. Inclui Mediator Abstractions, Refit, FluentValidation e FluentResults.</Description>
    <IncludeSymbols>false</IncludeSymbols>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddPlaceholderFile</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Refit" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="AddPlaceholderFile">
    <Touch Files="$(IntermediateOutputPath)_._" AlwaysCreate="true" />
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(IntermediateOutputPath)_._">
        <PackagePath>lib/$(TargetFramework)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>

</Project>
