<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Version>0.0.0</Version>
    <Authors>Marcus Vinicius de Freitas Costa</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://www.nuget.org/packages/MVFC.Pack.IoC</PackageProjectUrl>
    <PackageTags>ioc;dependency-injection;mediator;source-generator;fluentvalidation;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/Marcus-V-Freitas/MVFC.Pack.IoC</RepositoryUrl>
    <Description>Metapackage para padronizar e acelerar a configuração de inversão de controle (IoC) em aplicações .NET 9 | 10. Inclui Mediator (Source Generator), ServiceScan, FluentValidation DI e HttpClientFactory.</Description>
    <IncludeSymbols>false</IncludeSymbols>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddPlaceholderFile</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ServiceScan.SourceGenerator">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="AddPlaceholderFile">
    <Touch Files="$(IntermediateOutputPath)_._" AlwaysCreate="true" />
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(IntermediateOutputPath)_._">
        <PackagePath>lib/$(TargetFramework)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>

</Project>
