<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <Version>0.0.0</Version>
    <Authors>Marcus Vinicius de Freitas Costa</Authors>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <IsPackable>true</IsPackable>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://www.nuget.org/packages/MVFC.Pack.Analyzers</PackageProjectUrl>
    <PackageTags>analyzers;roslyn;sonar;code-quality;linting;csharp;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/Marcus-V-Freitas/MVFC.Pack.Analyzers</RepositoryUrl>
    <Description>Metapackage focado em garantir a qualidade, legibilidade e segurança no código C# através de análise estática contínua com SonarAnalyzer, Roslynator e NetAnalyzers. Suporta .NET 9 e .NET 10.</Description>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <IncludeSymbols>false</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Meziantou.Analyzer">
      <PrivateAssets>none</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <Content Include=".editorconfig">
      <Pack>true</Pack>
      <PackagePath>build/</PackagePath>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="build/MVFC.Pack.Analyzers.targets">
      <Pack>true</Pack>
      <PackagePath>build/</PackagePath>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="AddPlaceholderFile" BeforeTargets="_GetPackageFiles">
    <Touch Files="$(IntermediateOutputPath)_._" AlwaysCreate="true" />
    <ItemGroup>
      <None Include="$(IntermediateOutputPath)_._" Pack="true" PackagePath="lib/$(TargetFramework)/_._" />
    </ItemGroup>
  </Target>
  
</Project>